default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  username: root
  password: password

development:
  <<: *default
  database: metahub_development
  host: 127.0.0.1
  username: root
  password: password

test:
  <<: *default
  database: metahub_test

production:
  <<: *default
  host: 192.168.1.39
  database: metahub_production
  username: root
  password: <%= ENV["DATABASE_PASSWORD"] %>
